apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: lesson-controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lesson-controller-manager
  namespace: system
  labels:
    control-plane: lesson-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: lesson-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: lesson-controller-manager
    spec:
      securityContext:
        runAsUser: 65532
      containers:
      - args:
        - --leader-elect
        - --games-server-image games-server-image #TODO see if this works....
        image: lesson-controller
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
