apiVersion: apps/v1
kind: Deployment
metadata:
  name: matcher-deployment
  labels:
    app: matcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: matcher
  template:
    metadata:
      labels:
        app: matcher
    spec:
      containers:
      - name: matcher
        image: matcher-image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: 128Mi
